# Generated by Django 2.1.4 on 2019-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0002_auto_20190118_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
