# Generated by Django 2.1.4 on 2019-01-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0005_businessopportunitiy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='businessopportunitiy',
            new_name='businessopportunity',
        ),
    ]
