# Generated by Django 2.1.4 on 2019-01-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0006_auto_20190122_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='businessopportunity',
        ),
    ]
