# Generated by Django 2.1.4 on 2019-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0008_business_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_opportunity',
            name='restaurant_id',
            field=models.IntegerField(null=True),
        ),
    ]
