# Generated by Django 2.1.4 on 2019-01-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0009_auto_20190122_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='business_opportunity',
        ),
    ]
