# Generated by Django 2.1.4 on 2019-01-22 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0010_delete_business_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(null=True)),
                ('business_requirement', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date_inserted', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
