# Generated by Django 2.1.4 on 2019-01-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosiac', '0011_business_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(null=True)),
                ('business_opportunity_id', models.IntegerField(null=True)),
                ('employee_id', models.IntegerField(null=True)),
                ('contacted_person', models.CharField(max_length=100, null=True)),
                ('meeting_date', models.DateField(null=True)),
                ('meeting_description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
